version: '3.4'

services:
  mysql: 
    image: mysql
    ports:
      - 3333:3306
    environment:
      MYSQL_DATABASE: "faculdade"
      MYSQL_ROOT_PASSWORD: "leoq15/*"


  webapp:
    image: webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    ports:
      - 8080:80